"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret! This
# dev-only default is already public (it's committed in this repo's git
# history), so a production deploy MUST set DJANGO_SECRET_KEY explicitly —
# the guard below refuses to start otherwise. Generate one with:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
_DEV_SECRET_KEY = 'django-insecure-0a8qxqx6)%5zpwn1&yc#$y1+k6sqs+t=4a!if+gy#swc)xo6q8'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _DEV_SECRET_KEY)

if not DEBUG and SECRET_KEY == _DEV_SECRET_KEY:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be set to a real, privately-generated key in production. '
        'Refusing to start with the dev-only default key (which is public in git history).'
    )

ALLOWED_HOSTS = [
    host for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if host
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'entries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE = ['debug_toolbar.middleware.DebugToolbarMiddleware'] + MIDDLEWARE
    INTERNAL_IPS = ['127.0.0.1']

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'entries:home'
LOGOUT_REDIRECT_URL = 'login'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'entries.context_processors.announcements',
                'entries.context_processors.survey_prompt',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {'default': dj_database_url.config(conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Production hardening — inert locally since DEBUG=True by default there.
# Fly.io terminates TLS at its edge proxy and forwards plain HTTP to the app,
# setting X-Forwarded-Proto so Django can tell the request was originally HTTPS.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 60
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    CSRF_TRUSTED_ORIGINS = [
        origin for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if origin
    ]


# Email (used for the "forgot password" flow). Defaults to printing emails to
# the console/server log when DEBUG, since there's no mail server locally;
# set DJANGO_EMAIL_BACKEND plus the EMAIL_* vars below for a real SMTP relay
# in production.
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@thewaxtablet.local')

# Where "request access" notifications are sent for the admin to approve/reject.
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'jpelting@gmail.com')


# Weather (used by the morning check-in page)

WEATHER_LOCATION_NAME = 'Mount Holly, NC'
WEATHER_LATITUDE = 35.29819
WEATHER_LONGITUDE = -81.01591
WEATHER_TIMEZONE = 'America/New_York'


# Field-level encryption for journal content (see entries/fields.py). Keys are
# comma-separated, newest first — MultiFernet encrypts with the first key and
# tries each in turn to decrypt, so old ciphertext keeps working after rotation.
# The dev-only default below must NEVER be used in production: if it is, every
# encrypted row becomes unrecoverable the moment someone rotates or loses it.
# Generate a real key with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# and store it (and back it up somewhere durable, separate from the deploy
# host) as the FIELD_ENCRYPTION_KEYS env var. Losing this key permanently
# loses every user's journal content — there is no recovery path.
_DEV_FIELD_ENCRYPTION_KEY = 'ts_rr8XS8pdufcswNsIkqaD8OPJ0vln8RBI71eN1nNU='
FIELD_ENCRYPTION_KEYS = [
    key for key in os.environ.get('FIELD_ENCRYPTION_KEYS', _DEV_FIELD_ENCRYPTION_KEY).split(',') if key
]

if not DEBUG and _DEV_FIELD_ENCRYPTION_KEY in FIELD_ENCRYPTION_KEYS:
    raise ImproperlyConfigured(
        'FIELD_ENCRYPTION_KEYS must be set to a real, privately-generated key in production. '
        'Refusing to start with the dev-only default key.'
    )


# Bible passage text for devotional prompts is hand-curated from the King James Version
# (public domain, no permission/attribution required) in entries/data/devotional_prompts.json.
#
# entries/bible.py can optionally fetch verse text live from the YouVersion Platform API
# instead, for devotional prompts added one-off through the admin without seed data — get a
# free App Key at https://platform.youversion.com and set it as an env var (never commit it)
# if you want that fallback. Without a key it silently no-ops and the hand-curated KJV text
# (if any) is used as-is.

YVP_APP_KEY = os.environ.get('YVP_APP_KEY', '')
BIBLE_VERSION_ID = '111'  # NIV, used only for the optional live-fetch fallback above
BIBLE_VERSION_ATTRIBUTION = "King James Version (KJV), public domain."
