# Generated by Django 6.0.7 on 2026-08-04 02:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevotionalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text="Scripture reference, e.g. 'Philippians 4:6-7'.", max_length=100)),
                ('verse_text', models.TextField(blank=True, help_text='The passage text, if you want it displayed.')),
                ('reflection_prompt', models.TextField(help_text='A guiding question for the devotional reflection.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StoicPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='A stoic reflection prompt, e.g. quoting Marcus Aurelius, Seneca, Epictetus.')),
                ('source', models.CharField(blank=True, help_text="Optional attribution, e.g. 'Meditations, Book 4'.", max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mental_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('physical_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('emotional_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('spiritual_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('checkin_notes', models.TextField(blank=True)),
                ('stoic_response', models.TextField(blank=True)),
                ('devotional_response', models.TextField(blank=True)),
                ('freeform_entry', models.TextField(blank=True)),
                ('exercise_completed', models.BooleanField(default=False)),
                ('exercise_type', models.CharField(blank=True, max_length=100)),
                ('exercise_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise_notes', models.TextField(blank=True)),
                ('devotional_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entries.devotionalprompt')),
                ('stoic_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entries.stoicprompt')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-date'],
            },
        ),
    ]
