# Generated by Django 6.0.7 on 2026-08-05 02:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_seed_prompts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='checkin_notes',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='emotional_score',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='mental_score',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='physical_score',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='spiritual_score',
        ),
        migrations.AddField(
            model_name='entry',
            name='evening_emotional_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='evening_mental_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='evening_physical_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='evening_spiritual_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='morning_emotional_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='morning_mental_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='morning_physical_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='morning_spiritual_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='one_percent_goal',
            field=models.TextField(blank=True, help_text='One small thing that would make today 1% better.'),
        ),
        migrations.AddField(
            model_name='entry',
            name='one_percent_goal_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='weather_summary',
            field=models.CharField(blank=True, help_text='Cached weather snapshot from the morning check-in.', max_length=200),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='entries.entry')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MomentCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('emotions', models.CharField(blank=True, help_text='Comma-separated emotion tags.', max_length=300)),
                ('note', models.TextField(blank=True, help_text='What are you feeling, and why?')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moments', to='entries.entry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
