# Generated by Django 6.0.7 on 2026-08-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_remove_entry_checkin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotionalprompt',
            name='context_summary',
            field=models.TextField(blank=True, help_text='Brief context/meaning summary shown under the verse text.'),
        ),
    ]
