# Generated by Django 6.0.7 on 2026-08-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_devotionalprompt_context_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoicprompt',
            name='context_summary',
            field=models.TextField(blank=True, default='', help_text='Brief context about the quote/author shown under the quote.'),
        ),
        migrations.AddField(
            model_name='stoicprompt',
            name='reflection_prompt',
            field=models.TextField(blank=True, default='', help_text='A guiding question for the reflection.'),
        ),
        migrations.AlterField(
            model_name='stoicprompt',
            name='text',
            field=models.TextField(help_text='A stoic quote, e.g. from Marcus Aurelius, Seneca, Epictetus.'),
        ),
    ]
