# Generated by Django 6.0.7 on 2026-08-08 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_fix_stoic_practice_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrospectionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_year', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('question', models.TextField()),
            ],
            options={
                'ordering': ['day_of_year'],
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='exercise_completed',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='exercise_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='exercise_notes',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='exercise_type',
        ),
        migrations.AddField(
            model_name='entry',
            name='introspection_response',
            field=models.TextField(blank=True),
        ),
    ]
