# Generated by Django 6.0.7 on 2026-08-09 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_introspectionprompt_remove_entry_exercise_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('reference', models.CharField(blank=True, help_text='Scripture reference for the opening quote.', max_length=100)),
                ('occasion', models.CharField(blank=True, help_text="e.g. 'Christmas Day', 'For Sunday Morning'.", max_length=100)),
                ('quote', models.TextField(blank=True, help_text='The opening scripture quote.')),
                ('body', models.TextField(help_text='The prayer text.')),
                ('attribution', models.CharField(blank=True, help_text='Original contributor, if known.', max_length=200)),
            ],
            options={
                'ordering': ['month', 'day'],
                'constraints': [models.UniqueConstraint(fields=('month', 'day'), name='unique_prayer_month_day')],
            },
        ),
    ]
