# Generated by Django 6.0.7 on 2026-08-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_prayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='evening_could_improve',
            field=models.TextField(blank=True, help_text='If I could rewrite today, how would my ideal self respond to those exact situations?'),
        ),
        migrations.AddField(
            model_name='entry',
            name='evening_did_well',
            field=models.TextField(blank=True, help_text='Where did I show patience, discipline, or focus?'),
        ),
        migrations.AddField(
            model_name='entry',
            name='evening_gratitude_audit',
            field=models.TextField(blank=True, help_text="One thing I'd deeply miss if it were permanently taken away tomorrow."),
        ),
        migrations.AddField(
            model_name='entry',
            name='evening_where_falter',
            field=models.TextField(blank=True, help_text='Did I lose my temper, complain, procrastinate, or let my ego take over?'),
        ),
        migrations.AddField(
            model_name='entry',
            name='morning_anxious_about',
            field=models.TextField(blank=True, help_text='What am I anxious about today?'),
        ),
        migrations.AddField(
            model_name='entry',
            name='morning_reserve_clause',
            field=models.TextField(blank=True, help_text="Today's biggest event, held with “Fate permitting.”"),
        ),
        migrations.AddField(
            model_name='entry',
            name='morning_within_control',
            field=models.TextField(blank=True, help_text='What part of this is 100% in my control?'),
        ),
        migrations.AddField(
            model_name='entry',
            name='weekly_stoic_practice',
            field=models.CharField(blank=True, help_text="The specific Stoic exercise you're practicing this week.", max_length=300),
        ),
    ]
