# Generated by Django 6.0.7 on 2026-08-09 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_entry_evening_could_improve_entry_evening_did_well_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoicPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('part', models.CharField(blank=True, help_text="e.g. 'The Discipline of Desire'.", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='weekly_stoic_practice',
        ),
    ]
