# Generated by Django 6.0.7 on 2026-08-12 01:42

import entries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_encrypt_existing_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='devotional_response',
            field=entries.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='evening_could_improve',
            field=entries.fields.EncryptedTextField(blank=True, help_text='If I could rewrite today, how would my ideal self respond to those exact situations?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='evening_did_well',
            field=entries.fields.EncryptedTextField(blank=True, help_text='Where did I show patience, discipline, or focus?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='evening_gratitude_audit',
            field=entries.fields.EncryptedTextField(blank=True, help_text="One thing I'd deeply miss if it were permanently taken away tomorrow."),
        ),
        migrations.AlterField(
            model_name='entry',
            name='evening_where_falter',
            field=entries.fields.EncryptedTextField(blank=True, help_text='Did I lose my temper, complain, procrastinate, or let my ego take over?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='freeform_entry',
            field=entries.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='introspection_response',
            field=entries.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='morning_anxious_about',
            field=entries.fields.EncryptedTextField(blank=True, help_text='What am I anxious about today?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='morning_reserve_clause',
            field=entries.fields.EncryptedTextField(blank=True, help_text="Today's biggest event, held with “Fate permitting.”"),
        ),
        migrations.AlterField(
            model_name='entry',
            name='morning_within_control',
            field=entries.fields.EncryptedTextField(blank=True, help_text='What part of this is 100% in my control?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='one_percent_goal',
            field=entries.fields.EncryptedTextField(blank=True, help_text='One small thing that would make today 1% better.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='stoic_response',
            field=entries.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='text',
            field=entries.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='momentcheckin',
            name='note',
            field=entries.fields.EncryptedTextField(blank=True, help_text='What are you feeling, and why?'),
        ),
    ]
