# Generated by Django 6.0.7 on 2026-08-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='forecast_summary',
            field=models.CharField(blank=True, help_text="Cached tomorrow's forecast from the evening check-in.", max_length=200),
        ),
    ]
