# Generated by Django 6.0.7 on 2026-08-16 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('feature', 'New feature'), ('fix', 'Bug fix'), ('improvement', 'Improvement')], default='feature', max_length=15)),
                ('title', models.CharField(help_text="Short plain-language headline, e.g. 'Dictation now works on Safari'.", max_length=150)),
                ('description', models.TextField(help_text='1-2 short sentences in plain language, no technical jargon.')),
                ('location', models.CharField(blank=True, help_text="Where to find it, e.g. 'Morning Check-in'. Leave blank for bug fixes with nothing new to find.", max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop showing this in the popup.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen_announcement_at',
            field=models.DateTimeField(blank=True, help_text="When this user last dismissed the What's New popup.", null=True),
        ),
    ]
