# Generated by Django 6.0.7 on 2026-08-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0022_logincount'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotionalprompt',
            name='meaning_summary',
            field=models.TextField(blank=True, help_text='2-3 sentences explaining what the passage means.'),
        ),
        migrations.AlterField(
            model_name='devotionalprompt',
            name='context_summary',
            field=models.TextField(blank=True, help_text='2-3 sentences of historical/authorial context: who wrote it, to whom, and why.'),
        ),
        migrations.AlterField(
            model_name='devotionalprompt',
            name='reflection_prompt',
            field=models.TextField(help_text="A question asking how the passage's principle could be applied in a modern way in the user's life."),
        ),
    ]
