# Generated by Django 6.0.7 on 2026-08-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0023_devotionalprompt_meaning_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introspectionprompt',
            name='principle_summary',
            field=models.TextField(default='', help_text='2-3 sentences explaining the principle or idea behind the question, shown before it.'),
            preserve_default=False,
        ),
    ]
