# Generated by Django 6.0.7 on 2026-08-17 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0024_introspectionprompt_principle_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1. Overall, how satisfied are you with The Wax Tablet so far?', null=True)),
                ('most_used_section', models.CharField(blank=True, choices=[('checkin_morning', 'Morning Check-in'), ('checkin_evening', 'Evening Check-in'), ('stoic', 'Stoic Journal'), ('devotional', 'Devotional'), ('freeform', 'Freeform Journal'), ('introspection', 'Introspection')], help_text='2. Which section do you use most?', max_length=20)),
                ('least_used_section', models.CharField(blank=True, choices=[('checkin_morning', 'Morning Check-in'), ('checkin_evening', 'Evening Check-in'), ('stoic', 'Stoic Journal'), ('devotional', 'Devotional'), ('freeform', 'Freeform Journal'), ('introspection', 'Introspection')], help_text='2. Which section do you use least?', max_length=20)),
                ('feature_request', models.TextField(blank=True, help_text='3. If you could add or expand one feature, what would it be?')),
                ('friction_feedback', models.TextField(blank=True, help_text='4. Has anything been confusing, slow, or frustrating to use?')),
                ('reported_bug', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='5. Have you reported any bugs or glitches while using the app?', max_length=3)),
                ('bug_response_time_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='6. How satisfied were you with how quickly it was addressed? (shown if Q5 is yes)', null=True)),
                ('appearance_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text="7. What do you think of the app's look and feel?", null=True)),
                ('appearance_change', models.TextField(blank=True, help_text='8. What would you change about the appearance?')),
                ('content_helpful', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='9. Did you find the content helpful?', max_length=3)),
                ('favorite_part', models.TextField(blank=True, help_text='10. What was your favorite part? (shown if Q9 is yes)')),
                ('disliked_part', models.TextField(blank=True, help_text='11. What did you not enjoy or use and why? (shown if Q9 is no)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
