# Generated by Django 6.0.7 on 2026-08-19 01:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0025_surveyresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logincount',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text="Last authenticated request seen from this user, updated on any page view (not just sign-in). Powers the admin 'active now' view.", null=True),
        ),
        migrations.CreateModel(
            name='FeatureUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('checkin_morning', 'Morning Check-in'), ('checkin_evening', 'Evening Check-in'), ('checkin_moment', 'Moment Check-in'), ('calendar', 'Calendar'), ('journals_hub', 'Journals Hub'), ('journal_stoic', 'Journals: Stoic'), ('journal_devotional', 'Journals: Devotional'), ('journal_freeform', 'Journals: Freeform'), ('journal_introspection', 'Journals: Introspection'), ('entry_create', 'New Entry'), ('entry_edit', 'Edit Entry'), ('entry_detail', 'View Entry'), ('export', 'Export'), ('account', 'Account'), ('feedback', 'Feedback'), ('survey', 'Survey')], max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['feature', 'date'], name='entries_fea_feature_e4d6b1_idx')],
                'unique_together': {('user', 'feature', 'date')},
            },
        ),
    ]
