# Generated by Django 6.0.7 on 2026-08-21 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0026_logincount_last_activity_at_featureusageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, 'Morning'), (2, 'Evening')], default=1)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['day_of_year', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('day_of_year', 'slot'), name='unique_motivational_quote_day_slot')],
            },
        ),
    ]
