# Generated by Django 6.0.7 on 2026-08-22 00:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0028_profile_last_evening_quote_sent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affirmation_evening_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='affirmation_evening_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='profile',
            name='affirmation_morning_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='affirmation_morning_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name='profile',
            name='affirmations_enabled',
            field=models.BooleanField(default=False, help_text='Master opt-in for daily self-affirmations (desktop display and/or mobile push).'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_evening_affirmation_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_morning_affirmation_sent_date',
            field=models.DateField(blank=True, help_text='Dedupes push sends within the same day across cron ticks.', null=True),
        ),
        migrations.CreateModel(
            name='SelfAffirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, 'Morning'), (2, 'Evening')], default=1)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['day_of_year', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('day_of_year', 'slot'), name='unique_self_affirmation_day_slot')],
            },
        ),
    ]
