# Generated by Django 6.0.7 on 2026-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0030_community_communitymembership_community_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=10),
        ),
    ]
