# Generated by Django 6.0.7 on 2026-08-23 16:08

import datetime
import django.db.models.deletion
import django.utils.timezone
import entries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0031_communitymembership_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='last_prayer_digest_sent_date',
            field=models.DateField(blank=True, help_text='Dedupes digest sends within the same day across cron ticks.', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='prayer_digest_time',
            field=models.TimeField(default=datetime.time(20, 0), help_text='Daily time (set by the community admin) that pending prayer requests are bundled into one digest email.'),
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], max_length=10)),
                ('text', entries.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('immediate_sent_at', models.DateTimeField(blank=True, help_text='When the instant email/push went out, for an immediate request.', null=True)),
                ('digest_sent_at', models.DateTimeField(blank=True, help_text="When this request was included in the community's daily digest email.", null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='entries.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
