# Generated by Django 6.0.7 on 2026-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0032_community_last_prayer_digest_sent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text="Hides the requester's name in the community listing and in emails."),
        ),
    ]
