# Generated by Django 6.0.7 on 2026-08-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0033_prayerrequest_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='admin_agreement_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the creator accepted the Community Admin Agreement to create this community.', null=True),
        ),
    ]
