# Generated by Django 6.0.7 on 2026-08-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0034_community_admin_agreement_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembership',
            name='user_agreement_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When this member accepted the Community User Agreement to request joining.', null=True),
        ),
    ]
