# Generated by Django 6.0.7 on 2026-08-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0035_communitymembership_user_agreement_accepted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementGenState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sha', models.CharField(blank=True, max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
