# Generated by Django 6.0.7 on 2026-08-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0036_announcementgenstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved - invite code sent, awaiting entry'), ('active', 'Active')], default='active', max_length=10),
        ),
    ]
