# Generated by Django 6.0.7 on 2026-08-26 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0037_alter_communitymembership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checkin_reminder_enabled',
            field=models.BooleanField(default=False, help_text='Master opt-in for a daily push reminder to check in.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='checkin_reminder_evening_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='checkin_reminder_evening_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='profile',
            name='checkin_reminder_morning_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='checkin_reminder_morning_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_evening_checkin_reminder_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_morning_checkin_reminder_sent_date',
            field=models.DateField(blank=True, help_text='Dedupes push sends within the same day across cron ticks.', null=True),
        ),
    ]
