# Generated by Django 6.0.7 on 2026-08-26 00:50

import entries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0038_profile_checkin_reminder_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentcheckin',
            name='deep_dive_why_1',
            field=entries.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='momentcheckin',
            name='deep_dive_why_2',
            field=entries.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='momentcheckin',
            name='deep_dive_why_3',
            field=entries.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='momentcheckin',
            name='deep_dive_why_4',
            field=entries.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='momentcheckin',
            name='deep_dive_why_5',
            field=entries.fields.EncryptedTextField(blank=True),
        ),
    ]
