# Generated by Django 6.0.7 on 2026-08-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0039_momentcheckin_deep_dive_why_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='evening_gratitude_audit',
            new_name='evening_gratitude',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='morning_reserve_clause',
            new_name='morning_todays_commitment',
        ),
        migrations.AlterField(
            model_name='stoicpractice',
            name='part',
            field=models.CharField(blank=True, help_text="e.g. 'Desire'.", max_length=100),
        ),
    ]
