# Generated by Django 6.0.7 on 2026-08-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0040_rename_evening_gratitude_audit_entry_evening_gratitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureusageevent',
            name='feature',
            field=models.CharField(choices=[('checkin_morning', 'Morning Check-in'), ('checkin_evening', 'Evening Check-in'), ('checkin_moment', 'Moment Check-in'), ('calendar', 'Calendar'), ('journals_hub', 'Journals Hub'), ('journal_stoic', 'Journals: Stoic'), ('journal_devotional', 'Journals: Devotional'), ('journal_freeform', 'Journals: Freeform'), ('journal_introspection', 'Journals: Introspection'), ('entry_create', 'New Entry'), ('entry_edit', 'Edit Entry'), ('entry_detail', 'View Entry'), ('export', 'Export'), ('account', 'Account'), ('feedback', 'Feedback'), ('survey', 'Survey'), ('community', 'Community'), ('prayer_request', 'Prayer Request'), ('quote', 'Motivational Quote'), ('affirmation', 'Self-Affirmation')], max_length=30),
        ),
    ]
