# Generated by Django 6.0.7 on 2026-08-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0041_alter_featureusageevent_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_reengagement_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Dedupes across cron ticks - only sent again after activity resumes and inactivity recurs.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reengagement_emails_enabled',
            field=models.BooleanField(default=True, help_text="Send a 'come back' email after a stretch of inactivity. On by default; opt out below."),
        ),
    ]
