# Generated by Django 6.0.7 on 2026-09-01 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0042_profile_last_reengagement_email_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincount',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Last authenticated request seen from this user, updated on any page view (not just sign-in). Powers the admin 'active now' view.", null=True),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'status'], name='entries_com_communi_c9599f_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['user', 'status'], name='entries_com_user_id_0ffab3_idx'),
        ),
    ]
