# Generated by Django 6.0.7 on 2026-09-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0043_alter_logincount_last_activity_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronMaintenanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_session_cleanup_date', models.DateField(blank=True, help_text='Last time expired sessions were purged via `clearsessions`.', null=True)),
            ],
        ),
    ]
