# Generated by Django 6.0.7 on 2026-09-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0044_cronmaintenancestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='last_prayer_digest_reminder_sent_date',
            field=models.DateField(blank=True, help_text="Dedupes the admin's 1-hour-before-digest reminder email within the same day across cron ticks.", null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='immediate_approved_at',
            field=models.DateTimeField(blank=True, help_text="When the community admin approved this immediate request for an instant email/push. Only meaningful for request_type='immediate' - the instant notification is held back until this is set.", null=True),
        ),
    ]
