# Generated by Django 6.0.7 on 2026-09-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0045_community_last_prayer_digest_reminder_sent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Dedupes the one-time survey email - sent at most once ever per user.', null=True),
        ),
    ]
