# Generated by Django 6.0.7 on 2026-09-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0046_surveyresponse_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reengagement_emails_sent_count',
            field=models.PositiveIntegerField(default=0, help_text="How many reengagement emails have gone out in the current inactivity episode - drives which stage's interval applies next (see entries.reengagement). Reset to 0 once the user is active again and a new episode starts."),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_reengagement_email_sent_at',
            field=models.DateTimeField(blank=True, help_text="Dedupes across cron ticks - the next send waits for the current stage's interval to pass.", null=True),
        ),
    ]
